configfile: "defaults/config.yaml"

include: "rules/provision_metadata.smk"
include: "rules/sequence_counts.smk"
include: "rules/mlr_estimates.smk"
include: "rules/fitness_flux_analysis.smk"
include: "rules/mutation_counts.smk"
include: "rules/lineage_deltas_analysis.smk"

# Default target: the full workflow, including the analysis results/ tables.
# Defined after the includes so it can reference the per-stage aggregator rules.
rule all:
    default_target: True
    input:
        rules.all_sequence_counts.input,
        rules.all_variant_relationships.input,
        rules.all_mlr_estimates.input,
        rules.all_fitness_flux.input,
        rules.all_lineage_deltas.input,

# Per-virus convenience targets: the full pipeline for one pathogen. SARS-CoV-2 is
# fetched unsigned from a public bucket, so `nextstrain build --docker . sarscov2`
# runs end-to-end with no AWS credentials; H3N2 reads a private bucket (needs
# credentials). Upstream sequence-count and MLR jobs are pulled in as dependencies.
rule sarscov2:
    input:
        fitness_flux_outputs_for([a for a in FITNESS_FLUX_ANALYSES if a.startswith("sarscov2")]),
        rules.all_lineage_deltas.input,
        FITNESS_FLUX_VIZ_META,

rule h3n2:
    input:
        fitness_flux_outputs_for([a for a in FITNESS_FLUX_ANALYSES if a.startswith("h3n2")]),
        FITNESS_FLUX_VIZ_META,

rule clean:
    """
    Remove everything the workflow generates so the repo can be rerun from
    scratch: the upstream sequence-counts/ and mlr-estimates/, the logs, the
    analysis results/, and the generated viz component data/ and meta.json.
    Leaves the provisioned raw metadata in data/ and the component source in
    viz/ in place.
    """
    shell:
        """
        rm -rf sequence-counts \
               mlr-estimates \
               logs \
               fitness-flux-analysis/results \
               lineage-deltas-analysis/results \
               viz/time-vs-fitness/data viz/time-vs-fitness/meta.json \
               viz/time-vs-frequency/data viz/time-vs-frequency/meta.json \
               viz/frequency-vs-fitness/data viz/frequency-vs-fitness/meta.json \
               viz/variance-vs-flux/data viz/variance-vs-flux/meta.json
        """

rule clean_analysis:
    """
    Remove only the analysis intermediates generated by the fitness-flux and
    lineage-deltas rules (the results/ tables and the generated viz component
    data/ and meta.json), leaving the upstream sequence-counts/ and
    mlr-estimates/ outputs intact.
    """
    shell:
        """
        rm -rf fitness-flux-analysis/results \
               lineage-deltas-analysis/results \
               logs/fitness_flux \
               logs/lineage_deltas \
               viz/time-vs-fitness/data viz/time-vs-fitness/meta.json \
               viz/time-vs-frequency/data viz/time-vs-frequency/meta.json \
               viz/frequency-vs-fitness/data viz/frequency-vs-fitness/meta.json \
               viz/variance-vs-flux/data viz/variance-vs-flux/meta.json
        """
